// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Downloading a simple video in .mp4 format
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uIDLTuberClient = this.UIDLTuberWindow.UIDLTuberClient;
            WinRadioButton uIMp4RadioButton = this.UIDLTuberWindow.UIMp4Window.UIMp4RadioButton;
            WinButton uIDownloadButton = this.UIDLTuberWindow.UIDownloadWindow.UIDownloadButton;
            WinComboBox uIFilenameComboBox = this.UISaveAsWindow.UIDetailsPanePane.UIFilenameComboBox;
            WinButton uISaveButton = this.UISaveAsWindow.UISaveWindow.UISaveButton;
            WinButton uICloseButton = this.UIDownloadProgressWindow.UIDownloadProgressTitleBar.UICloseButton;
            WinButton uICloseButton1 = this.UIDLTuberWindow.UIDLTuberTitleBar.UICloseButton;
            #endregion

            // Click 'DLTuber' client
            Mouse.Click(uIDLTuberClient, new Point(410, 230));

            // Select 'mp4' radio button
            uIMp4RadioButton.Selected = this.RecordedMethod1Params.UIMp4RadioButtonSelected;

            // Click 'Download' button
            Mouse.Click(uIDownloadButton, new Point(62, 14));

            // Select 'devel' in 'File name:' combo box
            uIFilenameComboBox.EditableItem = this.RecordedMethod1Params.UIFilenameComboBoxEditableItem;

            // Click '&Save' button
            Mouse.Click(uISaveButton, new Point(53, 5));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(18, 28));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(38, 13));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIDLTuberWindow UIDLTuberWindow
        {
            get
            {
                if ((this.mUIDLTuberWindow == null))
                {
                    this.mUIDLTuberWindow = new UIDLTuberWindow();
                }
                return this.mUIDLTuberWindow;
            }
        }
        
        public UISaveAsWindow UISaveAsWindow
        {
            get
            {
                if ((this.mUISaveAsWindow == null))
                {
                    this.mUISaveAsWindow = new UISaveAsWindow();
                }
                return this.mUISaveAsWindow;
            }
        }
        
        public UIDownloadProgressWindow UIDownloadProgressWindow
        {
            get
            {
                if ((this.mUIDownloadProgressWindow == null))
                {
                    this.mUIDownloadProgressWindow = new UIDownloadProgressWindow();
                }
                return this.mUIDownloadProgressWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIDLTuberWindow mUIDLTuberWindow;
        
        private UISaveAsWindow mUISaveAsWindow;
        
        private UIDownloadProgressWindow mUIDownloadProgressWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Select 'mp4' radio button
        /// </summary>
        public bool UIMp4RadioButtonSelected = true;
        
        /// <summary>
        /// Select 'devel' in 'File name:' combo box
        /// </summary>
        public string UIFilenameComboBoxEditableItem = "devel";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDLTuberWindow : WinWindow
    {
        
        public UIDLTuberWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = " DLTuber";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add(" DLTuber");
            #endregion
        }
        
        #region Properties
        public WinClient UIDLTuberClient
        {
            get
            {
                if ((this.mUIDLTuberClient == null))
                {
                    this.mUIDLTuberClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIDLTuberClient.SearchProperties[WinControl.PropertyNames.Name] = " DLTuber";
                    this.mUIDLTuberClient.WindowTitles.Add(" DLTuber");
                    #endregion
                }
                return this.mUIDLTuberClient;
            }
        }
        
        public UIMp4Window UIMp4Window
        {
            get
            {
                if ((this.mUIMp4Window == null))
                {
                    this.mUIMp4Window = new UIMp4Window(this);
                }
                return this.mUIMp4Window;
            }
        }
        
        public UIDownloadWindow UIDownloadWindow
        {
            get
            {
                if ((this.mUIDownloadWindow == null))
                {
                    this.mUIDownloadWindow = new UIDownloadWindow(this);
                }
                return this.mUIDownloadWindow;
            }
        }
        
        public UIDLTuberTitleBar UIDLTuberTitleBar
        {
            get
            {
                if ((this.mUIDLTuberTitleBar == null))
                {
                    this.mUIDLTuberTitleBar = new UIDLTuberTitleBar(this);
                }
                return this.mUIDLTuberTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIDLTuberClient;
        
        private UIMp4Window mUIMp4Window;
        
        private UIDownloadWindow mUIDownloadWindow;
        
        private UIDLTuberTitleBar mUIDLTuberTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMp4Window : WinWindow
    {
        
        public UIMp4Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "mp4RadioBtn";
            this.WindowTitles.Add(" DLTuber");
            #endregion
        }
        
        #region Properties
        public WinRadioButton UIMp4RadioButton
        {
            get
            {
                if ((this.mUIMp4RadioButton == null))
                {
                    this.mUIMp4RadioButton = new WinRadioButton(this);
                    #region Search Criteria
                    this.mUIMp4RadioButton.SearchProperties[WinRadioButton.PropertyNames.Name] = "mp4";
                    this.mUIMp4RadioButton.WindowTitles.Add(" DLTuber");
                    #endregion
                }
                return this.mUIMp4RadioButton;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mUIMp4RadioButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDownloadWindow : WinWindow
    {
        
        public UIDownloadWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "selectVideo";
            this.WindowTitles.Add(" DLTuber");
            #endregion
        }
        
        #region Properties
        public WinButton UIDownloadButton
        {
            get
            {
                if ((this.mUIDownloadButton == null))
                {
                    this.mUIDownloadButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDownloadButton.SearchProperties[WinButton.PropertyNames.Name] = "Download ";
                    this.mUIDownloadButton.WindowTitles.Add(" DLTuber");
                    #endregion
                }
                return this.mUIDownloadButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDownloadButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDLTuberTitleBar : WinTitleBar
    {
        
        public UIDLTuberTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add(" DLTuber");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add(" DLTuber");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISaveAsWindow : WinWindow
    {
        
        public UISaveAsWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Save As";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Save As");
            #endregion
        }
        
        #region Properties
        public UIDetailsPanePane UIDetailsPanePane
        {
            get
            {
                if ((this.mUIDetailsPanePane == null))
                {
                    this.mUIDetailsPanePane = new UIDetailsPanePane(this);
                }
                return this.mUIDetailsPanePane;
            }
        }
        
        public UISaveWindow UISaveWindow
        {
            get
            {
                if ((this.mUISaveWindow == null))
                {
                    this.mUISaveWindow = new UISaveWindow(this);
                }
                return this.mUISaveWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDetailsPanePane mUIDetailsPanePane;
        
        private UISaveWindow mUISaveWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDetailsPanePane : WinPane
    {
        
        public UIDetailsPanePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Details Pane";
            this.WindowTitles.Add("Save As");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIFilenameComboBox
        {
            get
            {
                if ((this.mUIFilenameComboBox == null))
                {
                    this.mUIFilenameComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIFilenameComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "File name:";
                    this.mUIFilenameComboBox.WindowTitles.Add("Save As");
                    #endregion
                }
                return this.mUIFilenameComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIFilenameComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISaveWindow : WinWindow
    {
        
        public UISaveWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Save As");
            #endregion
        }
        
        #region Properties
        public WinButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[WinButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.WindowTitles.Add("Save As");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDownloadProgressWindow : WinWindow
    {
        
        public UIDownloadProgressWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Download Progress";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Download Progress");
            #endregion
        }
        
        #region Properties
        public UIDownloadProgressTitleBar UIDownloadProgressTitleBar
        {
            get
            {
                if ((this.mUIDownloadProgressTitleBar == null))
                {
                    this.mUIDownloadProgressTitleBar = new UIDownloadProgressTitleBar(this);
                }
                return this.mUIDownloadProgressTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIDownloadProgressTitleBar mUIDownloadProgressTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDownloadProgressTitleBar : WinTitleBar
    {
        
        public UIDownloadProgressTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Download Progress");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Download Progress");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
